cache: redis

redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    COINBASE:
        retries: -1
        l3_book:
            symbols: [BTC-USD, ETH-USD, ETH-BTC]
            book_delta: true
            book_interval: 100000
        trades: [BTC-USD, ETH-USD, ETH-BTC]
        ticker: [BTC-USD, ETH-USD, ETH-BTC]

storage: [influx, parquet]
storage_retries: 10
storage_retry_wait: 30

influx:
    host: 'http://127.0.0.1:8086'
    db: cryptostore
    create: true
    username: cryptostore
    password: cryptostore
    token: 74GZNXC2xum7r95C_gM_nz_XaS0_iaMNYkDeFrPX7cHi4N5ciLnGzBelYJX1v8XL77qyi-3LV0-8OEXe0Kulwg==

parquet:
    del_file: false
    append_counter: 60
    compression:
        codec: 'BROTLI'
        level: 6
    path: /home/kaznak/work/cryptostore/data
    prefix_date: true

storage_interval: 60

