cache: redis

redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    COINBASE:
        retries: -1
        l3_book:
            symbols: [BTC-USD, ETH-USD, ETH-BTC]
            book_delta: true
            book_interval: 100000
        trades: [BTC-USD, ETH-USD, ETH-BTC]
        ticker: [BTC-USD, ETH-USD, ETH-BTC]

storage: [parquet]
storage_retries: 10
storage_retry_wait: 30

parquet:
    del_file: true
    append_counter: 60
    compression:
        codec: 'BROTLI'
        level: 6
    path: /home/kaznak/work/cryptoenv/data
    prefix_date: true
    GCS:
        service_account: null
        bucket: cryptofeed
        prefix: null

storage_interval: 60

